name: Build Docker image and push to docker registry

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      DOCKERHUB_REPOSITORY:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs: 
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          # Note: tags has to be all lower-case
          tags: |
           ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REPOSITORY }}:undertest
          # build on feature branches, push only on main branch
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          cache-from: type=registry,ref=${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REPOSITORY }}:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.build_docker_image.outputs.digest }}