name: Deploy image under test to Heroku for manual test

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      DOCKERHUB_REPOSITORY:
        required: true
        type: string
      HEROKU_REPOSITORY:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      HEROKU_API_KEY:
        required: true

jobs:     
  deploy_to_heroku_for_manual_test:
    #needs: [build_docker_image]
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub, deploy & release on Heroku test space
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login -u=_ --password-stdin registry.heroku.com
          docker pull ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REPOSITORY }}:undertest
          echo '--- DOCKER TAG ---'
          docker tag ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.DOCKERHUB_REPOSITORY }}:undertest registry.heroku.com/${{ inputs.HEROKU_REPOSITORY }}/web
          echo '--- PUSH HEROKU ---'
          docker push registry.heroku.com/${{ inputs.HEROKU_REPOSITORY }}/web
          echo '--- CONTAINER RELEASE --- ${{ secrets.HEROKU_API_KEY }}'
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web --app ${{ inputs.HEROKU_REPOSITORY }}